version: '3'

services:     
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    restart: unless-stopped
    deploy:
        resources:
          reservations:
            cpus: '0.001'
            memory: 20M
          limits:
            cpus: '0.02'
            memory: 100M
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - portainer_default
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    deploy:
        resources:
          reservations:
            cpus: '0.006'
            memory: 400M
          limits:
            cpus: '0.3'
            memory: 600M
    ports:
      - 9090
    volumes:
      - /root/grafana/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml 
#--web.config.file=/etc/prometheus/web.yml
    networks:
      - portainer_default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    deploy:
        resources:
          reservations:
            cpus: '0.0007'
            memory: 50M
          limits:
            cpus: '0.05'
            memory: 150M
    volumes:
      - /root/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - /root/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - /root/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - /root/grafana/dashboards/dashboard_provider.yml:/etc/grafana/provisioning/dashboards/dashboard_provider.yml
      - /root/grafana/dashboards/mydash.json:/etc/grafana/provisioning/dashboards/mydash.json
    networks:
    - portainer_default
    environment:
      GF_SECURITY_ADMIN_USER: kial1
      GF_SECURITY_ADMIN_PASSWORD: 898904ok

networks:
  portainer_default:
    name: portainer_default

volumes:
  prometheus-data:
  grafana-data: